#!/usr/bin/env bash -

# uninstall Oracle JDK7 alternative for update-alternatives --config java

update-alternatives --remove-all java 

# no need to specifically remove the slaved components, they're removed automatically with the master
#update-alternatives --remove-all appletviewer 
#update-alternatives --remove-all apt 
#update-alternatives --remove-all ControlPanel 
#update-alternatives --remove-all extcheck 
#update-alternatives --remove-all idlj 
#update-alternatives --remove-all jar 
#update-alternatives --remove-all jarsigner 
#update-alternatives --remove-all javac 
#update-alternatives --remove-all javadoc 
#update-alternatives --remove-all javah 
#update-alternatives --remove-all javap 
#update-alternatives --remove-all java-rmi.cgi 
#update-alternatives --remove-all javaws 
#update-alternatives --remove-all jconsole 
#update-alternatives --remove-all jcontrol 
#update-alternatives --remove-all jcmd 
#update-alternatives --remove-all jdb 
#update-alternatives --remove-all jhat 
#update-alternatives --remove-all jinfo 
#update-alternatives --remove-all jmap 
#update-alternatives --remove-all jps 
#update-alternatives --remove-all jrunscript 
#update-alternatives --remove-all jsadebugd 
#update-alternatives --remove-all jstack 
#update-alternatives --remove-all jstat 
#update-alternatives --remove-all jstatd 
#update-alternatives --remove-all jvisualvm 
#update-alternatives --remove-all keytool 
#update-alternatives --remove-all native2ascii 
#update-alternatives --remove-all orbd 
#update-alternatives --remove-all pack200 
#update-alternatives --remove-all policytool 
#update-alternatives --remove-all rmic 
#update-alternatives --remove-all rmid 
#update-alternatives --remove-all rmiregistry 
#update-alternatives --remove-all schemagen 
#update-alternatives --remove-all serialver 
#update-alternatives --remove-all servertool 
#update-alternatives --remove-all tnameserv 
#update-alternatives --remove-all unpack200
#update-alternatives --remove-all wsgen 
#update-alternatives --remove-all wsimport 
#update-alternatives --remove-all xjc 
#update-alternatives --remove-all dblook 
#update-alternatives --remove-all ij 
#update-alternatives --remove-all NetworkServerControl 
#update-alternatives --remove-all setEmbeddedCP 
#update-alternatives --remove-all setNetworkClientCP 
#update-alternatives --remove-all setNetworkServerCP 
#update-alternatives --remove-all startNetworkServer 
#update-alternatives --remove-all stopNetworkServer 
#update-alternatives --remove-all sysinfo 
#update-alternatives --remove-all man.java
